name: Integration
on:
  pull_request:
    paths:
      - .github/workflows/integration.yaml
      - Cargo.toml
      - Cargo.lock
      - flake.nix
      - flake.lock
      - ci/**
      - e2e/**
      - crates/**
      - tools/**
  push:
    branches: [master, main]
    paths:
      - .github/workflows/integration.yaml
      - Cargo.toml
      - Cargo.lock
      - flake.nix
      - flake.lock
      - ci/**
      - e2e/**
      - crates/**
      - tools/**

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 1
  CARGO_PROFILE_RELEASE_DEBUG: 1
  RUST_BACKTRACE: short
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

# Cancel previous runs of this workflow when a new commit is added to the PR, branch or tag
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        chain:
          - package: ibc-go-v8-simapp
            command: simd
            account_prefix: cosmos
            native_token: stake
            features: ica,ics29-fee,new-register-interchain-account,channel-upgrade,authz
          - package: ibc-go-v10-simapp
            command: simd
            account_prefix: cosmos
            native_token: stake
            features: ica,new-register-interchain-account,authz,no-denom-trace

    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with: 
          extra-conf: |
            substituters = https://cache.nixos.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with: 
          name: cosmos-nix
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p ibc-integration-test --features=${{ matrix.chain.features }} --no-fail-fast --no-run
      - name: Install cargo-nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: Run integration test
        env:
          RUST_LOG: info
          RUST_BACKTRACE: 1
          NO_COLOR_LOG: 1
          NEXTEST_RETRIES: 2
          CHAIN_COMMAND_PATHS: ${{ matrix.chain.command }}
          ACCOUNT_PREFIXES: ${{ matrix.chain.account_prefix }}
          NATIVE_TOKENS: ${{ matrix.chain.native_token }}
        run: |
            nix shell .#python .#${{ matrix.chain.package }} -c \
              cargo nextest run -p ibc-integration-test --no-fail-fast --failure-output final --test-threads=2 \
              --features=${{ matrix.chain.features }}
